drop table if exists tb_editora CASCADE;
drop table if exists tb_emprestimo_devolucao CASCADE;
drop table if exists tb_genero CASCADE;
drop table if exists tb_livro CASCADE;
drop table if exists tb_refresh_token CASCADE;
drop table if exists tb_role CASCADE;
drop table if exists tb_usuario CASCADE;
drop table if exists tb_usuario_role CASCADE;

create table tb_editora (
    id bigint generated by default as identity,
    nome varchar(255));

create table tb_emprestimo_devolucao (
     id bigint generated by default as identity,
     data_devolucao TIMESTAMP WITHOUT TIME ZONE,
     data_emprestimo TIMESTAMP WITHOUT TIME ZONE,
     situacao varchar(255),
     livro_id bigint,
     usuario_id bigint);

create table tb_genero (
   id bigint generated by default as identity,
   nome varchar(255));

create table tb_livro (
      id bigint generated by default as identity,
      ano_publicacao TIMESTAMP WITHOUT TIME ZONE,
      autor varchar(255),
      descricao varchar(255),
      edicao integer,
      img_url varchar(255),
      isbn varchar(255),
      quantidade integer,
      status varchar(255),
      titulo varchar(255),
      editora_id bigint,
      genero_id bigint);

create table tb_refresh_token (
      id bigint not null,
      expiry_date TIMESTAMP WITHOUT TIME ZONE not null,
      token varchar(255) not null,
      usuario_id bigint);

create table tb_role (
     id bigint generated by default as identity,
     autorizacao varchar(255));

create table tb_usuario (
    id bigint generated by default as identity,
    cep varchar(255),
    cidade varchar(255),
    complemento varchar(255),
    cpf varchar(255),
    email varchar(255),
    email_alternativo varchar(255),
    endereco varchar(255),
    estado varchar(255),
    nome varchar(255),
    numero_endereco varchar(255),
    senha varchar(255),
    sobrenome varchar(255),
    telefone varchar(255));

create table tb_usuario_role (
     usuario_id bigint not null,
     role_id bigint not null);

alter table tb_editora add primary key (id);
alter table tb_emprestimo_devolucao add primary key (id);
alter table tb_genero add primary key (id);
alter table tb_livro add primary key (id);
alter table tb_refresh_token add primary key (id);
alter table tb_role add primary key (id);
alter table tb_usuario add primary key (id);
alter table tb_usuario_role add primary key (usuario_id, role_id);

alter table tb_editora add constraint UK_3bem15f641duw36d572nxmqof unique (nome);
alter table tb_genero add constraint UK_dd2x15l6td591powhdwepvws2 unique (nome);
alter table tb_refresh_token add constraint UK_i63fy6f7kgr4uk9ndkxe5q8q4 unique (token);
alter table tb_usuario add constraint UK_594wib8ansybtilla48x7vdld unique (cpf);
alter table tb_usuario add constraint UK_spmnyb4dsul95fjmr5kmdmvub unique (email);
alter table tb_usuario add constraint UK_spmnyb4d4533434435kmdmvub unique (email_alternativo);

alter table tb_emprestimo_devolucao add constraint FKgasrwi0qsqfveawvt1atsws3r foreign key (livro_id) references tb_livro;
alter table tb_emprestimo_devolucao add constraint FKe3ueryttqbylojb1w3pr877i4 foreign key (usuario_id) references tb_usuario;
alter table tb_livro add constraint FKld4mxvtivc86lren384755w5r foreign key (editora_id) references tb_editora;
alter table tb_livro add constraint FKpxd9hjiepwc97r5nbhl012tas foreign key (genero_id) references tb_genero;
alter table tb_refresh_token add constraint FKsxt8uwpnqfv2976b16g0hrbp4 foreign key (usuario_id) references tb_usuario;
alter table tb_usuario_role add constraint FKkix4nwaehqjwnk40e2e36903j foreign key (role_id) references tb_role;
alter table tb_usuario_role add constraint FKj4syki71kai6syrfuly9xfcq foreign key (usuario_id) references tb_usuario;

insert into tb_role (autorizacao) values ('ROLE_USUARIO');
insert into tb_role (autorizacao) values ('ROLE_BIBLIOTECARIO');
insert into tb_role (autorizacao) values ('ROLE_ADMIN');