USE `DATABASE-MUSEUM`;

DELIMITER $$
CREATE PROCEDURE GRAFICO_QUANTIDADE_PESSOAS_POR_MES()
BEGIN
	SELECT 
		SUM(QUANTIDADE_PESSOAS) QUANTIDADE_PESSOAS_POR_MES, 
		EXTRACT(YEAR FROM DATA_RESERVA) ANO,
		EXTRACT(MONTH FROM DATA_RESERVA) MES
	FROM 
		TB_RESERVA
	GROUP BY
		ANO, MES
	ORDER BY 
		ANO, MES;
END$$
DELIMITER ;

CALL GRAFICO_QUANTIDADE_PESSOAS_POR_MES();
DROP PROCEDURE GRAFICO_QUANTIDADE_PESSOAS_POR_MES;

DELIMITER $$
CREATE PROCEDURE RELATORIO_VALOR_TOTAL_DOADO_POR_MES()
BEGIN
	SET lc_time_names = 'pt_BR';
	SELECT 
		CONVERT(SUM(VALOR_DOADO), DECIMAL(65,2)) VALOR_TOTAL_DOADO_POR_MES, 
		EXTRACT(YEAR FROM DATA_DOACAO) ANO,
		MONTHNAME(STR_TO_DATE(EXTRACT(MONTH FROM DATA_DOACAO), '%m')) MES
	FROM 
		TB_DOACAO
	GROUP BY
		ANO, MES
	ORDER BY 
		ANO, MES;
END$$
DELIMITER ;

CALL RELATORIO_VALOR_TOTAL_DOADO_POR_MES();
DROP PROCEDURE RELATORIO_VALOR_TOTAL_DOADO_POR_MES;